sonar.projectKey=flutter-lm-feed-sdk
sonar.projectName=Flutter LM Feed SDK
sonar.token=sqp_2526c79807b6d7e206aab3e8118cd0cfd2c4ae8f
sonar.host.url=http://localhost:9000
sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.exclusions=test/**/*_test.mocks.dart,lib/**/*.g.dart