// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'chatroom_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ChatroomEntity _$ChatroomEntityFromJson(Map<String, dynamic> json) =>
    ChatroomEntity(
      access: json['access'],
      accessWithoutSubscription: json['access_without_subscription'] as bool,
      answerText: json['answer_text'] as String,
      answersCount: json['answers_count'] as int,
      attachmentCount: json['attachment_count'] as int,
      attachmentsUploaded: json['attachments_uploaded'] as bool,
      attended: json['attended'] as bool,
      attendingCount: json['attending_count'] as int,
      attendingStatus: json['attending_status'] as bool,
      audioCount: json['audio_count'] as int,
      autoFollowDone: json['auto_follow_done'] as bool,
      cardCreationTime: json['card_creation_time'] as String,
      chatRequestCreatedAt: json['chat_request_created_at'],
      chatRequestState: json['chat_request_state'],
      chatRequestedBy: json['chat_requested_by'],
      cohorts: json['cohorts'] as List<dynamic>,
      communityId: json['community_id'] as int,
      communityName: json['community_name'] as String,
      createdAt: json['created_at'] as int,
      customTag: json['custom_tag'] as String,
      date: json['date'] as String,
      dateEpoch: json['date_epoch'] as int,
      dateTime: json['date_time'] as int,
      duration: json['duration'] as int,
      eventKind: json['event_kind'] as String,
      externalSeen: json['external_seen'] as bool,
      followStatus: json['follow_status'] as bool,
      header: json['header'] as String,
      id: json['id'] as int,
      imageCount: json['image_count'] as int,
      includeMembersLater: json['include_members_later'] as bool,
      isEdited: json['is_edited'] as bool,
      isGuest: json['is_guest'] as bool,
      isPaid: json['is_paid'] as bool,
      isPending: json['is_pending'] as bool,
      isPinned: json['is_pinned'] as bool,
      isPrivate: json['is_private'] as bool,
      isPrivateMember: json['is_private_member'] as bool,
      isSecret: json['is_secret '] as bool,
      isTagged: json['is_tagged'] as bool,
      member: UserEntity.fromJson(json['member'] as Map<String, dynamic>),
      memberCanMessage: json['member_can_message'] as bool,
      muteStatus: json['mute_status'] as bool,
      onlineLinkEnableBefore: json['online_link_enable_before'] as int,
      onlineLinkType: json['online_link_type'],
      participantsCount: json['participants_count'] as int,
      pdfCount: json['pdf_count'] as int,
      pollsCount: json['polls_count'] as int,
      reactions: json['reactions'] as List<dynamic>,
      shareLink: json['share_link'] as String,
      state: json['state'] as int,
      thirdPartyUniqueId: json['third_party_unique_id'],
      title: json['title'] as String,
      totalResponseCount: json['total_response_count'] as int,
      type: json['type'] as int,
      updatedAt: json['updated_at'] as int,
      videoCount: json['video_count'] as int,
    );

Map<String, dynamic> _$ChatroomEntityToJson(ChatroomEntity instance) =>
    <String, dynamic>{
      'access': instance.access,
      'access_without_subscription': instance.accessWithoutSubscription,
      'answer_text': instance.answerText,
      'answers_count': instance.answersCount,
      'attachment_count': instance.attachmentCount,
      'attachments_uploaded': instance.attachmentsUploaded,
      'attended': instance.attended,
      'attending_count': instance.attendingCount,
      'attending_status': instance.attendingStatus,
      'audio_count': instance.audioCount,
      'auto_follow_done': instance.autoFollowDone,
      'card_creation_time': instance.cardCreationTime,
      'chat_request_created_at': instance.chatRequestCreatedAt,
      'chat_request_state': instance.chatRequestState,
      'chat_requested_by': instance.chatRequestedBy,
      'cohorts': instance.cohorts,
      'community_id': instance.communityId,
      'community_name': instance.communityName,
      'created_at': instance.createdAt,
      'custom_tag': instance.customTag,
      'date': instance.date,
      'date_epoch': instance.dateEpoch,
      'date_time': instance.dateTime,
      'duration': instance.duration,
      'event_kind': instance.eventKind,
      'external_seen': instance.externalSeen,
      'follow_status': instance.followStatus,
      'header': instance.header,
      'id': instance.id,
      'image_count': instance.imageCount,
      'include_members_later': instance.includeMembersLater,
      'is_edited': instance.isEdited,
      'is_guest': instance.isGuest,
      'is_paid': instance.isPaid,
      'is_pending': instance.isPending,
      'is_pinned': instance.isPinned,
      'is_private': instance.isPrivate,
      'is_private_member': instance.isPrivateMember,
      'is_secret ': instance.isSecret,
      'is_tagged': instance.isTagged,
      'member': instance.member,
      'member_can_message': instance.memberCanMessage,
      'mute_status': instance.muteStatus,
      'online_link_enable_before': instance.onlineLinkEnableBefore,
      'online_link_type': instance.onlineLinkType,
      'participants_count': instance.participantsCount,
      'pdf_count': instance.pdfCount,
      'polls_count': instance.pollsCount,
      'reactions': instance.reactions,
      'share_link': instance.shareLink,
      'state': instance.state,
      'third_party_unique_id': instance.thirdPartyUniqueId,
      'title': instance.title,
      'total_response_count': instance.totalResponseCount,
      'type': instance.type,
      'updated_at': instance.updatedAt,
      'video_count': instance.videoCount,
    };
