class FeedRoom {
  // "about_recording": null,
  //           "access": null,
  //           "access_without_subscription": false,
  //           "answer_text": "",
  //           "answers_count": 0,
  //           "attachment_count": 0,
  //           "attachments_uploaded": false,
  //           "attended": false,
  //           "attending_count": 0,
  //           "attending_status": false,
  //           "audio_count": 0,
  //           "auto_follow_done": false,
  //           "card_creation_time": "01:04 PM",
  //           "chat_request_created_at": null,
  //           "chat_request_state": null,
  //           "chat_requested_by": null,
  //           "chatroom_image_url": "https://i.pravatar.cc/400",
  //           "co_hosts": [],
  //           "cohorts": [],
  //           "community_id": 50447,
  //           "community_name": "Flutter GC Example",
  //           "created_at": "13:04",
  //           "date": "31 Jan 2023",
  //           "date_epoch": 1675150463,
  //           "date_time": 0,
  //           "duration": 0,
  //           "external_seen": true,
  //           "follow_status": true,
  //           "has_been_named": true,
  //           "header": "Test feedroom ABC",
  //           "id": 72200,
  //           "image_count": 0,
  //           "include_members_later": false,
  //           "is_edited": false,
  //           "is_guest": false,
  //           "is_paid": false,
  //           "is_pending": false,
  //           "is_pinned": false,
  //           "is_private": false,
  //           "is_private_member": false,
  //           "is_secret": false,
  //           "is_tagged": false,
  //           "member": {
  //               "community_id": 50447,
  //               "created_at": 1673613302,
  //               "custom_title": "Owner",
  //               "id": 87103,
  //               "image_url": "",
  //               "is_guest": false,
  //               "is_owner": true,
  //               "member_since": "Member since Jan 13 2023",
  //               "name": "Flutter GC Example bot",
  //               "route": "route://member_community_profile?community_id=50447&member_id=87103",
  //               "state": 1,
  //               "user_unique_id": "22b6a64f-66bf-4bca-800e-b40ca66f924d"
  //           },
  //           "member_can_message": true,
  //           "member_id": 87103,
  //           "mute_status": false,
  //           "online_link_enable_before": 900000,
  //           "online_link_type": null,
  //           "participants_count": 2,
  //           "pdf_count": 0,
  //           "polls_count": 0,
  //           "reactions": [],
  //           "recording_url_og_tags": null,
  //           "recordings_attachments": [],
  //           "recordings_attachments_view": 0,
  //           "recordings_url": [],
  //           "share_link": "",
  //           "show_follow_auto_tag": false,
  //           "show_follow_telescope": false,
  //           "state": 0,
  //           "third_party_unique_id": "",
  //           "title": "Test feedroom ABC",
  //           "total_response_count": 0,
  //           "type": 11,
  //           "video_count": 0

  // final String? audioRecording;
  // final String? access;
  // final bool accessWithoutSubscription;

}
