// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'feedroom_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

FeedRoomEntity _$FeedRoomEntityFromJson(Map<String, dynamic> json) =>
    FeedRoomEntity(
      id: json['id'] as int,
      title: json['title'] as String,
      header: json['header'] as String,
      date: json['date'] as String,
      dateEpoch: json['date_epoch'] as int?,
      dateTime: json['date_time'] as int?,
      duration: json['duration'] as int?,
      cardCreationTime: json['card_creation_time'] as String?,
      shareLink: json['share_link'] as String?,
      thirdPartyUniqueId: json['third_party_unique_id'] as String?,
      state: json['state'] as int,
      isPrivate: json['is_private'] as bool?,
      isSecret: json['is_secret'] as bool?,
      isPending: json['is_pending'] as bool?,
      isPrivateMember: json['is_private_member'] as bool?,
      isTagged: json['is_tagged'] as bool?,
      isGuest: json['is_guest'] as bool?,
      isPaid: json['is_paid'] as bool?,
      isPinned: json['is_pinned'] as bool?,
      isEdited: json['is_edited'] as bool?,
      hasBeenNamed: json['has_been_named'] as bool?,
      autoFollowDone: json['auto_follow_done'] as bool?,
      includeMembersLater: json['include_members_later'] as bool?,
      accessWithoutSubscription: json['access_without_subscription'] as bool?,
      externalSeen: json['external_seen'] as bool?,
      showFollowTelescope: json['show_follow_telescope'] as bool?,
      showFollowAutoTag: json['show_follow_auto_tag'] as bool?,
      memberCanMessage: json['member_can_message'] as bool?,
      muteStatus: json['mute_status'] as bool?,
      followStatus: json['follow_status'] as bool?,
      communityId: json['community_id'] as int,
      communityName: json['community_name'] as String?,
      chatroomImageUrl: json['chatroom_image_url'] as String?,
      onlineLinkEnableBefore: json['online_link_enable_before'] as int?,
      onlineLinkType: json['online_link_type'] as String?,
      participantsCount: json['participants_count'] as int,
      uuid: json['uuid'] as String?,
      access: json['access'] as String?,
      member: UserEntity.fromJson(json['member'] as Map<String, dynamic>),
      cohorts: json['cohorts'] as List<dynamic>?,
      coHosts: json['co_hosts'] as List<dynamic>?,
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] == null
          ? null
          : DateTime.fromMillisecondsSinceEpoch(json['updated_at'] as int),
      customTag: json['custom_tag'] as String?,
      eventKind: json['event_kind'] as String?,
      imageCount: json['image_count'] as int?,
      videoCount: json['video_count'] as int?,
      pdfCount: json['pdf_count'] as int?,
      pollsCount: json['polls_count'] as int?,
      totalResponseCount: json['total_response_count'] as int?,
      reactions: json['reactions'] as List<dynamic>?,
      type: json['type'] as int?,
      memberId: json['member_id'] as int?,
    );

Map<String, dynamic> _$FeedRoomEntityToJson(FeedRoomEntity instance) =>
    <String, dynamic>{
      'id': instance.id,
      'title': instance.title,
      'header': instance.header,
      'date': instance.date,
      'date_epoch': instance.dateEpoch,
      'date_time': instance.dateTime,
      'duration': instance.duration,
      'card_creation_time': instance.cardCreationTime,
      'share_link': instance.shareLink,
      'third_party_unique_id': instance.thirdPartyUniqueId,
      'state': instance.state,
      'is_private': instance.isPrivate,
      'is_secret': instance.isSecret,
      'is_pending': instance.isPending,
      'is_private_member': instance.isPrivateMember,
      'is_tagged': instance.isTagged,
      'is_guest': instance.isGuest,
      'is_paid': instance.isPaid,
      'is_pinned': instance.isPinned,
      'is_edited': instance.isEdited,
      'has_been_named': instance.hasBeenNamed,
      'auto_follow_done': instance.autoFollowDone,
      'include_members_later': instance.includeMembersLater,
      'access_without_subscription': instance.accessWithoutSubscription,
      'external_seen': instance.externalSeen,
      'show_follow_telescope': instance.showFollowTelescope,
      'show_follow_auto_tag': instance.showFollowAutoTag,
      'member_can_message': instance.memberCanMessage,
      'mute_status': instance.muteStatus,
      'follow_status': instance.followStatus,
      'community_id': instance.communityId,
      'community_name': instance.communityName,
      'chatroom_image_url': instance.chatroomImageUrl,
      'online_link_enable_before': instance.onlineLinkEnableBefore,
      'online_link_type': instance.onlineLinkType,
      'participants_count': instance.participantsCount,
      'uuid': instance.uuid,
      'access': instance.access,
      'member': instance.member,
      'cohorts': instance.cohorts,
      'co_hosts': instance.coHosts,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt?.millisecondsSinceEpoch,
      'custom_tag': instance.customTag,
      'event_kind': instance.eventKind,
      'image_count': instance.imageCount,
      'video_count': instance.videoCount,
      'pdf_count': instance.pdfCount,
      'polls_count': instance.pollsCount,
      'total_response_count': instance.totalResponseCount,
      'reactions': instance.reactions,
      'type': instance.type,
      'member_id': instance.memberId,
    };
