# Main Github Actions CI/CD file
name: Merge to development

on:
  push:
    branches:
      - development

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  build-and-dry-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Prints the current branch name
        run: echo "${GITHUB_BRANCH}"

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Dry run for pub.dev
        run: flutter pub publish --dry-run
