# Main Github Actions CI/CD file
name: Merge to master

on:
  pull_request:
    branches:
      - mock-master
  push:
    branches:
      - mock-master

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prints the current branch name
        run: echo "${GITHUB_BRANCH}"

      - name: Checkout the repository
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ env.BRANCH_NAME }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2 #plugin for setting up the java
        with:
          distribution: "zulu"
          java-version: "11" #define the java version

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.0 #Flutter latest version defined
      - name: Set up Flutter and dependencies
        run: flutter pub get

      - name: Run PROD tests
        run: flutter test

      - name: Get version
        id: yq
        uses: mikefarah/yq@master
        with:
          cmd: yq -r '.version' 'pubspec.yaml'

      - name: Print version and set in env
        run: echo "VERSION_CODE=$(echo ${{ steps.yq.outputs.result }} | cut -c 1-6)" >> $GITHUB_ENV

      - name: Test
        run: echo "The latest version is $VERSION_CODE"

      - name: Make a new release and tag
        uses: avakar/tag-and-release@v1
        with:
          tag_name: "test-v${{ env.VERSION_CODE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
