# Main Github Actions CI/CD file
name: Feed SDK test on every PR
on:
  pull_request:
    branches-ignore: #exclude the branches from the test
      - main
jobs:
  run-flutter-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2 #plugin for setting up the java
        with:
          distribution: "zulu"
          java-version: "11" #define the java version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.0 #Flutter latest version defined
      - run: flutter pub get #installing the plugins for the flutter project
      - run: flutter test --dart-define=DEBUG=true
